In [5]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [6]:
#2. Print the NUMPY version and the configuration.
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Arnau/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Arnau/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Arnau/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Arnau/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Arnau/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Arnau/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Arnau/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Arnau/anaconda3\\Library\\include']


In [7]:
#3. Generate a 2x3x5 3-dimensional array with random values.
#Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. 
#How many ways can you find? one
a = np.random.random((2,3,5))

In [8]:
#4. Print a.
a

array([[[0.54122143, 0.29394776, 0.39433515, 0.98615522, 0.2438442 ],
        [0.92123349, 0.92361391, 0.17855195, 0.53843505, 0.65797333],
        [0.54238632, 0.81519148, 0.13468008, 0.35685224, 0.09328805]],

       [[0.78708453, 0.32906167, 0.49241609, 0.4902423 , 0.06147967],
        [0.67899252, 0.86031725, 0.82226614, 0.33009282, 0.34786725],
        [0.69910859, 0.57237564, 0.48789653, 0.94614846, 0.15348179]]])

In [9]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [10]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [12]:
#8. Are you able to add a and b? Why or why not?
#ab = a + b
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
b.shape

(5, 2, 3)

In [14]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=np.transpose(b, (1, 2, 0))


In [15]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=a+c
d

array([[[1.54122143, 1.29394776, 1.39433515, 1.98615522, 1.2438442 ],
        [1.92123349, 1.92361391, 1.17855195, 1.53843505, 1.65797333],
        [1.54238632, 1.81519148, 1.13468008, 1.35685224, 1.09328805]],

       [[1.78708453, 1.32906167, 1.49241609, 1.4902423 , 1.06147967],
        [1.67899252, 1.86031725, 1.82226614, 1.33009282, 1.34786725],
        [1.69910859, 1.57237564, 1.48789653, 1.94614846, 1.15348179]]])

In [16]:
#11. Print a and d.
#Notice the difference and relation of the two array in terms of the values? Explain.
#It is a plus 1 
print(a)
print(d)


[[[0.54122143 0.29394776 0.39433515 0.98615522 0.2438442 ]
  [0.92123349 0.92361391 0.17855195 0.53843505 0.65797333]
  [0.54238632 0.81519148 0.13468008 0.35685224 0.09328805]]

 [[0.78708453 0.32906167 0.49241609 0.4902423  0.06147967]
  [0.67899252 0.86031725 0.82226614 0.33009282 0.34786725]
  [0.69910859 0.57237564 0.48789653 0.94614846 0.15348179]]]
[[[1.54122143 1.29394776 1.39433515 1.98615522 1.2438442 ]
  [1.92123349 1.92361391 1.17855195 1.53843505 1.65797333]
  [1.54238632 1.81519148 1.13468008 1.35685224 1.09328805]]

 [[1.78708453 1.32906167 1.49241609 1.4902423  1.06147967]
  [1.67899252 1.86031725 1.82226614 1.33009282 1.34786725]
  [1.69910859 1.57237564 1.48789653 1.94614846 1.15348179]]]


In [17]:
#12. Multiply a and c. Assign the result to e.
e=a*c
e

array([[[0.54122143, 0.29394776, 0.39433515, 0.98615522, 0.2438442 ],
        [0.92123349, 0.92361391, 0.17855195, 0.53843505, 0.65797333],
        [0.54238632, 0.81519148, 0.13468008, 0.35685224, 0.09328805]],

       [[0.78708453, 0.32906167, 0.49241609, 0.4902423 , 0.06147967],
        [0.67899252, 0.86031725, 0.82226614, 0.33009282, 0.34786725],
        [0.69910859, 0.57237564, 0.48789653, 0.94614846, 0.15348179]]])

In [18]:
#13. Does e equal to a? Why or why not?
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [19]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.986155221499008
1.0614796713857448
1.5226846978165602


In [20]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
f

array([[[0.54122143, 0.29394776, 0.39433515, 0.98615522, 0.2438442 ],
        [0.92123349, 0.92361391, 0.17855195, 0.53843505, 0.65797333],
        [0.54238632, 0.81519148, 0.13468008, 0.35685224, 0.09328805]],

       [[0.78708453, 0.32906167, 0.49241609, 0.4902423 , 0.06147967],
        [0.67899252, 0.86031725, 0.82226614, 0.33009282, 0.34786725],
        [0.69910859, 0.57237564, 0.48789653, 0.94614846, 0.15348179]]])

In [21]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [25]:
f=np.where(d==d_min,0,
          np.where((d> d_min)&(d<d_mean),25,
                  np.where(d==d_mean,50,
                          np.where((d> d_mean)&(d<d_max),75,100)
                          )
                  )
          )
f

array([[[ 75,  25,  25, 100,  25],
        [ 75,  75,  25,  75,  75],
        [ 75,  75,  25,  25,  25]],

       [[ 75,  25,  25,  25,   0],
        [ 75,  75,  75,  25,  25],
        [ 75,  75,  25,  75,  25]]])

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [26]:
for ind, sub_arr in enumerate(d):
#     print(ind, sub_arr)
#     print()
    for ind_sub, sub_sub_arr in enumerate(sub_arr):
#         print(ind_sub, sub_sub_arr)
#         print()
        for ind_sub_sub, element in enumerate(sub_sub_arr):
#             print(ind_sub_sub, element)
            if element == d_min:
                f[ind][ind_sub][ind_sub_sub] = 0
            elif element > d_min and element < d_mean:
                f[ind][ind_sub][ind_sub_sub] = 25
            elif element == d_mean:
                f[ind][ind_sub][ind_sub_sub] = 50
            elif element > d_mean and element < d_max:
                f[ind][ind_sub][ind_sub_sub] = 75
            else:
                f[ind][ind_sub][ind_sub_sub] = 100

print(f)

[[[ 75  25  25 100  25]
  [ 75  75  25  75  75]
  [ 75  75  25  25  25]]

 [[ 75  25  25  25   0]
  [ 75  75  75  25  25]
  [ 75  75  25  75  25]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [29]:
for ind, sub_arr in enumerate(d):
    g = np.empty((2,3,5), dtype="O")

    for ind_sub, sub_sub_arr in enumerate(sub_arr):
        for ind_sub_sub, element in enumerate(sub_sub_arr):
            if element == d_min:
                g[ind][ind_sub][ind_sub_sub] = A
            elif element > d_min and element < d_mean:
                g[ind][ind_sub][ind_sub_sub] = B
            elif element == d_mean:
                g[ind][ind_sub][ind_sub_sub] = C
            elif element > d_mean and element < d_max:
                g[ind][ind_sub][ind_sub_sub] = D
            else:
                g[ind][ind_sub][ind_sub_sub] = E 
print(g)

NameError: name 'D' is not defined